### ISSUE TITLE
clang-sf fails to compile the target program

### ISSUE THREAD

**Issue by enlighten5** [OleksiiOleksenko/SpecFuzz#10]
Hi,

I tried to compile test drivers for `Brotli`, `Libhtp` and `YAML` using `clang-sf`, but it failed due to some unexcepted errors. I think this might be a bug in `clang-sf` because it can compile when using vanilla `clang`. 

This doc contains the instructions and error logs of the compile process (https://docs.google.com/document/d/1VWShJXYEc304QOTrVnOMTwpnEaO7TUQxld2wP41MWUw/edit?usp=sharing). 
Hope this may help!

**Comment by OleksiiOleksenko** [comment]
Could you pass `--echo` to the compiler and post the build log?

**Comment by OleksiiOleksenko** [comment]
Also, could you try removing `-fPIC`? I haven't tested SpecFuzz with this flag.

**Comment by OleksiiOleksenko** [comment]
Take a look at the makefiles in `example/usesec20`, maybe they will help you figure out the issue.

**Comment by OleksiiOleksenko** [comment]
Update: I tried both `-fPIC` and `-static` with brotli, and I could not reproduce the issue. I'm going to need your compiler output with `--echo`.

**Comment by enlighten5** [comment]
Hi,

Thank you for sharing the makefiles. I quickly tried the makefiles and they all work. One question I have is that do we need to add `-fsanitize=address` flag in `common.mk`?  Is `-fsanitize=address` enabled by default or optional?

I will post the build log later.

Thank you!

**Comment by OleksiiOleksenko** [comment]
No, you don't need to add `-fsanitize=address`, the compiler wrapper takes care of it. You can see all the flags that are enabled by default if you invoke `clang-sf` with `--echo`. Or, you can take a look directly at the code, here: https://github.com/OleksiiOleksenko/SpecFuzz/blob/master/install/wrapper.sh
