### ISSUE TITLE
Problems building clang with the paches applied

### ISSUE THREAD

**Issue by andsanmar** [OleksiiOleksenko/SpecFuzz#12]
After following all the instructions o build `clang` v-7.0.1 (using the provided files and so on), when applying the patches and hen rebuilding LLVM with the provided Makefile, results in an error when compiling `asan_rtl.cc` (which belongs to `compiler-rt`).  attach a file containing the error messages produced, which are regarding to the regarding to bad register names and invalid instruction suffix (recall to the previous warnings too).

The process of building SpecFuzz is being really a pain, as I've spent almost 1 week without any result by far, asking to rewrite system binaries (clang), as long as the system where I'm trying it is pretty standard (Ubuntu 18.04 with i7-8550U). I suggest the creators to have any way of containerization or distribute the binaries directly as long as the build gives several errors. Hope this helps to improve the process.

[build_error.log](https://github.com/OleksiiOleksenko/SpecFuzz/files/4981142/build_error.log)

**Comment by OleksiiOleksenko** [comment]
> After following all the instructions o build clang v-7.0.1 (using the provided files and so on), when applying the patches and hen rebuilding LLVM with the provided Makefile, results in an error when compiling asan_rtl.cc (which belongs to compiler-rt). attach a file containing the error messages produced, which are regarding to the regarding to bad register names and invalid instruction suffix (recall to the previous warnings too).

Judging by the errors, you're trying to build it for a 32-bit architecture. SpecFuzz is not compatible with it.

> The process of building SpecFuzz is being really a pain, as I've spent almost 1 week without any result by far, asking to rewrite system binaries (clang), as long as the system where I'm trying it is pretty standard (Ubuntu 18.04 with i7-8550U). I suggest the creators to have any way of containerization or distribute the binaries directly as long as the build gives several errors. Hope this helps to improve the process.

Thank you, this is extremely helpful.

**Comment by andsanmar** [comment]
It seems weird, I've rebuilt the whole tooling again but gives an error which previously resulted in a warning (I changed the default system compiler to clang-10, which previously by somewhat was a 32-bit one). On which point should I add the flags or which default compiler should I use? I attach the file with the mentioned errors
[build_error.log](https://github.com/OleksiiOleksenko/SpecFuzz/files/4983179/build_error.log)

**Comment by andsanmar** [comment]
Finally, with gcc-8 and g++-8 as default compilers it has worked. Thanks for your support
