### ISSUE TITLE
visitIndirectBranch targets

### ISSUE THREAD

**Issue by AlonB644** [OleksiiOleksenko/SpecFuzz#17]
As with indirect calls, other indirect jumps can receive a register as operand

**Comment by AlonB644** [comment]
Is that intended?

**Comment by AlonB644** [comment]
As an example, a switch statement might be naively implemented with:
"jmpq *%rax"
AKA X86::JMP64r

**Comment by OleksiiOleksenko** [comment]
Sorry, I didn't get it. What is the bug?

Are you talking about the fact that the indirect jump targets are not checked for whether they are instrumented?

**Comment by AlonB644** [comment]
The problem is that the case of register operand isn't being handled or even checked. When compiling with no optimizations (-O0) switch statements tend to be implemented with an indirect jump and with a register operand that preserves jump target.
More concretely, "visitIndirectCall" uses "PointerIsInMemory" boolean and does handle the case that I'm talking about for indirect calls.

**Comment by AlonB644** [comment]
Example code:
[switch.txt](https://github.com/OleksiiOleksenko/SpecFuzz/files/5078523/switch.txt)

Example commands:
clang -O0 -ggdb switch.c -c -o switch.o 
             (uses "jmpq   *rcx")
clang-sf -O0 -ggdb switch.c -c -o switch.o 
             (fails because it can't handle "jmpq   *rcx" - expects target in memory)
clang-sf -O3 -ggdb switch.c -c -o switch.sf.o 
              (works because  of no usage of "jmpq   *rcx" instruction)

**Comment by OleksiiOleksenko** [comment]
Ah, now I get it. It fails on line 538, right? This one:

```
    BuildMI(Parent, MI, Loc, TII->get(X86::MOV64rm), X86::RDI)
        .add(MI.getOperand(X86::AddrBaseReg))
        .add(MI.getOperand(X86::AddrScaleAmt))
        .add(MI.getOperand(X86::AddrIndexReg))
        .add(MI.getOperand(X86::AddrDisp))
        .add(MI.getOperand(X86::AddrSegmentReg));
```
Yes, you're right. A register operand would require special handling. It's weird that this bug did not show up before.

I'm on it.
