### ISSUE TITLE
Reproducing the experiments on JSMN, Brotli, HTTP, libHTP, YAML, SSL

### ISSUE THREAD

**Issue by canertol** [OleksiiOleksenko/SpecFuzz#22]
Hi,

I want to reproduce the outputs given in Tables 5, 6, and 7 in the paper especially for **OpenSSL** and have some questions.

* Which files did you scan exactly in OpenSSL?
* I see a simple victim_function given in **demo.c** but how can we scan the OpenSSL files using the code given in the **example** folder?

Thanks in advance.

**Comment by OleksiiOleksenko** [comment]
Hi, 

See here: https://github.com/OleksiiOleksenko/SpecFuzz/tree/master/example/usesec20
