### ISSUE TITLE
Error compiling llvm

### ISSUE THREAD

**Issue by SpiralBL0CK** [OleksiiOleksenko/SpecFuzz#24]
when running sudo INSTALL_DIR=/llvm/installation/directory/ ./install/llvm.sh i get the following errors:
[ 14%] Built target RTfuzzer.x86_64
make: *** [Makefile:152: all] Error 2
/llvm/installation/directory/llvm-7.0.1/src/tools/compiler-rt-7.0.1.src/lib/sanitizer_common/sanitizer_internal_defs.h:342:70: error: size ‘-1’ of array ‘assertion_failed__1163’ is negative
  342 |     typedef char IMPL_PASTE(assertion_failed_##_, line)[2*(int)(pred)-1]
      |                                                         ~~~~~~~~~~~~~^~

**Comment by OleksiiOleksenko** [comment]
Hi,

Thanks for reporting!

These days I don't have much time for maintaining SpecFuzz, so I will look into it a bit later. Maybe next month. 

Meanwhile, if you find a solution yourself, please, post it here.

**Comment by OleksiiOleksenko** [comment]
The bug is described here: https://reviews.llvm.org/D69104.

The only way I found to work around it is to patch the native LLVM, as shown here: https://github.com/llvm/llvm-project/commit/947f9692440836dcb8d88b74b69dd379d85974ce
