### ISSUE TITLE
Handling Writes to Thread Local Storage

### ISSUE THREAD

**Issue by zzrcxb** [OleksiiOleksenko/SpecFuzz#25]
Minimal reproducible example:
```c
#include <stdio.h>

static __thread int x;

int main() {
    x = 10;
    printf("x = %d\n", x);
}
```
Compile it with `clang-sf` without optimization, running it will end up with an error:
```
[SF] Error: Signal handler called outside speculation
```

The instructions that caused the fault are (related to instrumentation on writes):
```assembly
leaq   %fs:x@TPOFF, %r15
movq   checkpoint_sp, %rsp
pushq  %r15
pushq  (%r15)  # faulting!
```

The root cause of this fault is the `leaq` instruction, which only computes the effective address and **ignores** segment registers like `%fs`. Therefore, `%r15` points to a wrong location, and `pushq (%r15)` will fail.

Potential workaround: emit the following code sequence for writes to TLS.
```assembly
leaq   x@TPOFF, %r14  # compute effective address
movq   %fs:0, %r15  # read %fs value
addq   %r14, %r15  # get linear address by adding them up
movq   checkpoint_sp, %rsp
pushq  %r15
pushq  (%r15)  # backup the old value
```

**Comment by OleksiiOleksenko** [comment]
Thanks for finding this issue.

Unfortunately, I do not maintain SpecFuzz anymore. However, if you can implement the workaround yourself, I will gladly accept the pull request.
