### ISSUE TITLE
Evaluation dataset availability

### ISSUE THREAD

**Issue by enlighten5** [OleksiiOleksenko/SpecFuzz#6]
Hi,

Thank you for open source this valuable work. 

I was wondering if it's possible to share the instructions to compile the six libraries used in the evaluation. 

Thank you in advance!

**Comment by OleksiiOleksenko** [comment]
Hi,
Sure. I cannot promise to add them in the immediate future, but I will add them.

**Comment by OleksiiOleksenko** [comment]
I added the experiments descriptions to `example/usesec20`.
