### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by enlighten5** [OleksiiOleksenko/SpecFuzz#8]
Hi,

I found this `UnicodeDecodeError: 'utf-8' codec can't decode byte` error when reading stdin in analyzer.py. But this only happens after I add one `printf` in my test driver and it may output something that cannot be decoced by `utf-8`. So I don't know if it's necessary to fix this. Anyway, I fixed it by adding this line of code in `collect_data()` function: `sys.stdin.reconfigure(encoding='ISO-8859-1')`

**Comment by OleksiiOleksenko** [comment]
Thanks for the report. I will investigate it.
